### ISSUE TITLE
How to supply a pull request

### ISSUE THREAD

**Issue by erdnussflips** [roest01/docker-speedtest-analyser#15]
Hi @roest01,

how to supply a pull request for a feature when forking is forbidden by your license?

Best regards
erdnussflips

**Comment by roest01** [comment]
Hey @erdnussflips,
please do a fork and do what you can + need to do.
I have to update readme if that isn't clear. 

Passage of forking came into readme because of [stuff like this](https://github.com/ntimo/docker-speedtest-analyser/commit/80ba90b9207e6ede3fbc6be8314a21729f057d3a).
please excuse the lack of clarity

**Comment by roest01** [comment]
solved as side product with #17
