### ISSUE TITLE
Request ping on different axis

### ISSUE THREAD

**Issue by SunX99** [roest01/docker-speedtest-analyser#18]
I was trying to dig around and find the graph styling to make a change. Here is my example:
I'm running a 40mbps down, 2mbps up DSL line, with pings swinging from 40ms to 900ms. With the ping and u/d speed on the same graph axis the visual changes in the up/down become very hard to see.
Was looking to try and make the ping on a separate graph or if it could be on a second axis like this example-
https://www.chartjs.org/samples/latest/charts/line/multi-axis.html
Is there an easy way to alter the graph?
Thanks for the easy docker image for logging speed issues.

**Comment by roest01** [comment]
Hey @SunX99 ,

I quite believe this issue was solved with #10 ?

because it's relevant as well:
You can suppress any line by clicking any item on the legend. 
This setting keeps enabled until you reload the page.
![legend](https://user-images.githubusercontent.com/2870718/52207974-601d4780-287f-11e9-9d8d-ca10e8513ea6.png)
