### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by andpill** [roest01/docker-speedtest-analyser#3]
I'm also getting the invalid date issue when I have a volume mounted in /var/www/html/data/ on my synology NAS. A bit of digging revealed that the result.csv file in /var/www/html/data/ when not mounted to the NAS has headers of timestamp,ping,download,upload but when this is mounted to somewhere on the NAS those headers are missing from the results.csv file. Manually adding timestamp,ping,download,upload to this file made the graph work for me.

Hopefully this makes sense to you as this is my 1st dip into doing anything with docker and synology.

Any questions I'm happy to provide whatever answers I can.

**Comment by roest01** [comment]
Hey andpill,

Thanks for your report. I'm thinking about this since some days now.

The [result.csv](https://raw.githubusercontent.com/roest01/docker-speedtest-analyser/master/data/result.csv) contains the required header right from the start. Mounting the directory onto the synology shouln't remove that file?!?

May i implement a checkup on write if that file exist? If there is no result.csv the code should init the file with correct header.

I've also think about the idea to move into an sqLITE (or alternative) database which allows me to generate reports. (average speed in past XY days/weeks, top speed, lowermost speed)

Just an update about my thoughts. What do you think?
roest

**Comment by roest01** [comment]
this fix is available in current [develop](https://hub.docker.com/r/roest/docker-speedtest-analyser/builds/bnccd4vmsj538dfrqjgdkcm/) and will be released with [v1.2](/roest01/docker-speedtest-analyser/milestone/3)
